version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "9898:4200"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "9876:9876"
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
